version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # These will override values in application.properties
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/translation_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=a_very_secure_jwt_secret_key_for_local_development_only_minimum_32_characters_long
      - JWT_EXPIRATION_MS=3600000 # 1 hour
      - GOOGLE_CLIENT_ID=your_google_client_id_from_google_cloud_console
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_from_google_cloud_console
      - GOOGLE_TRANSLATE_API_KEY=your_google_translate_api_key_if_you_have_one # Can be dummy-key for mock
      - FRONTEND_OAUTH_REDIRECT_URL=http://localhost:3000/oauth-callback
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG # Enable Spring Security DEBUG logging
    depends_on:
      - mysql_db
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    ports:
      - "3307:3306" # Exposing on 3307 on host to avoid conflict if local MySQL runs on 3306
    environment:
      - MYSQL_ROOT_PASSWORD=very_strong_root_password_123!
      - MYSQL_DATABASE=translation_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pass
    volumes:
      - mysql-data:/var/lib/mysql # Persist database data
    networks:
      - app_network

volumes:
  mysql-data: # Define the named volume

networks:
  app_network:
    driver: bridge
