version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET:-mercury_super_secure_jwt_secret_key_2025}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:-86400000}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY:-dummy-key}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
      - MERCURY_WELCOME_MESSAGE=${MERCURY_WELCOME_MESSAGE:-Welcome to Mercury User Service}
      - MERCURY_VERSION=${MERCURY_VERSION:-1.0.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
